#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 17 23:00:11 2020

@author: vitorino
"""

'''
Imprimir o resultado:
0 10
1 9
2 8
3 7
4 6
5 5
6 4
7 3
8 2
'''

for i, j in enumerate(range(10, 1, -1)):
    print(i, j)
    
for i in range(10):
   print(i, 10-i)
   if i == 8:
       break